# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


def initial_data(apps, schema_editor):
    BB = apps.get_model('building', 'Building')

    BB(name='Housing', cost=-1, maint=0, required=None, desc='Housing orders the workers to build additional living space. This increases the population growth rate of the colony slightly.').save()
    BB(name='Trade Goods', cost=-1, maint=0, required=None, desc='Trade Goods instructs the colonists to make items for sale to other colonies. The taxes on these transactions add to the income generated by this colony. Every 2 industry converts to 1 BC.').save()


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_populate_buildings'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]
