# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


def initial_data(apps, schema_editor):
    TC = apps.get_model('tech', 'TechCategory')
    T = apps.get_model('tech', 'Tech')

    tc = TC(name='Military Tactics', cost=150, category='SO')
    tc.save()
    T(name='Space Academy', categ=tc, desc="""Trains ship crews, adding 1 to their starting level. Ships stationed in the system gain 2 experience each turn.""").save()

    tc = TC(name='Xeno Relations', cost=650, category='SO')
    tc.save()
    T(name='Xeno Psychology', categ=tc, desc="""Focuses on the motivation of other races in an attempt to form deals that are more appealing. The effect is to permanently add +30 diplomatic points to every deal offered to your opponents.""").save()
    T(name='Alien Control Center', categ=tc, desc="""Provides better control of occupied alien populations: aliens work harder, assimilate into your empire twice as fast, and are half as likely to revolt.""").save()

    tc = TC(name='Macro Economics', cost=1150, category='SO')
    tc.save()
    T(name='Planetary Stock-Exchange', categ=tc, desc="""Increases the revenues earned on a planet by +100%.""").save()

    tc = TC(name='Teaching Methods', cost=2000, category='SO')
    tc.save()
    T(name='Astro University', categ=tc, desc="""Using the most advanced teaching methods available, the efficiency of farmers, workers, and scientists is increased. Each receives a +1 bonus.""").save()

    tc = TC(name='Advanced Government', cost=4500, category='SO')
    tc.save()
    # T(name='Confederation')
    T(name='Imperium', categ=tc, desc="""Advanced form of dictatorship. Total command points generated are increased by +50% and all defensive spy rolls are at +20.""").save()
    # T(name='Federation')
    # T(name='Galactic Unification')

    tc = TC(name='Galactic Economics', cost=6000, category='SO')
    tc.save()
    T(name='Galactic Currency Exchange', categ=tc, desc="""Eliminates the need for hard currency, replacing it with instantaneous electronic exchanges. Increases the money generated by all colonies by +50%.""").save()


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_chemistry_techs'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]

# EOF
